version: 0.2

phases:
  install:
    commands:
      - echo No dependencies to install
  build:
    commands:
      - echo No build step required

artifacts:
  files:
    - '**/*'  # Include all files in the artifacts
